### ISSUE TITLE
auto increment not carried across

### ISSUE THREAD

**Issue by jpike88** [AnatolyUss/nmig#103]

**Comment by AnatolyFromPerion** [comment]
Hello Josh,
Could you share a bit more details?

Do you have some custom auto-increment strategy and it doesn't work the same way in Postgres?

**Comment by jpike88** [comment]
sorry I moved onto AWS Schema conversion tool, my issue is less to do with full migration right now, and just getting a schema I can wrangle.... this is not an easy process!
