### ISSUE TITLE
process out of memory

### ISSUE THREAD

**Issue by emailgregn** [AnatolyUss/nmig#11]
Looks like a memory leak as usage steadily climbs until bust.  
Large mysql table ( 8,000,000 rows, 63 columns but none are TEXT). Machine has 4GB RAM
"data_chunk_size" : 32,

 
    
    <--- Last few GCs --->
    
      131383 ms: Scavenge 1396.3 (1460.3) -> 1396.3 (1460.3) MB, 0.6 / 0 ms (+ 3.1 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
      132672 ms: Mark-sweep 1396.3 (1460.3) -> 1395.5 (1460.3) MB, 1288.7 / 0 ms (+ 4.8 ms in 2 steps since start of marking, biggest step 3.1 ms) [last resort gc].
      133959 ms: Mark-sweep 1395.5 (1460.3) -> 1396.3 (1460.3) MB, 1287.7 / 0 ms [last resort gc].
    
    
    <--- JS stacktrace --->
    
    ==== JS stack trace =========================================
    
    Security context: 0x2b0326fe3ac1 <JS Object>
        1: stringify [/home/xxxx/src/nmig/migration/fmtp/csvStringifyModified.js:~209] [pc=0xcf9371cbcae] (this=0x6191bedd9a9 <JS Object>,line=0x8e7ee691059 <an Object with map 0x21cd8a610441>)
        2: write [/home/xxxx/src/nmig/migration/fmtp/csvStringifyModified.js:184] [pc=0xcf937106fd6] (this=0x6191bedd9a9 <JS Object>,chunk=0x8e7ee691059 <an Object with map 0x21cd8a610441>,encoding=0x2b032...
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
    Aborted

node --version

    v5.7.1

uname -a

    Linux xxx 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AnatolyUss** [comment]
Hi,
Try to either 
1. Use smaller value at "data_chunk_size" 
2. increase the memory limit <code>$ node --max-old-space-size=</code> before running nmig

Please, let me know if you'll have any other issue.

**Comment by emailgregn** [comment]
Tried with same results:
1. "data_chunk_size" = 2
2. $ node --max-old-space-size=2048 
3. Both together.

**Comment by AnatolyUss** [comment]
Is the error exactly the same?
Are you running nmig as follows: <code>node --max-old-space-size=2048 main.js
</code>?
Try "data_chunk_size" : 1
If nothing changes, try to use <a href="https://github.com/AnatolyUss/FromMySqlToPostgreSql">FromMySqlToPostgreSql</a>
BTW, what is the total size of you database (in GB)?

**Comment by emailgregn** [comment]
The trace is different but the end message is still out of memory.
Here it is with "data_chunk_size" : 1
Database is about 10GB


    $ node --max-old-space-size=2048 main.js 
    
    	NMIG - the database migration tool
    	Copyright 2016 Anatoly Khaytovich <anatolyuss@gmail.com>
    
    	--[boot] Boot...
    	--[readDataTypesMap] Data Types Map is loaded...
    	--[boot] Boot is accomplished...
    	--[createLogsDirectory] Creating logs directory...
    	--[createLogsDirectory] Logs directory already exists...
    	--[createTemporaryDirectory] Creating temporary directory...
    	--[createTemporaryDirectory] Temporary directory is created...
    	--[loadStructureToMigrate] Source DB structure is loaded...
    	--[loadStructureToMigrate] Tables to migrate: 6
    	--[loadStructureToMigrate] Views to migrate: 0
    	--[createTable] Currently creating table: `XXXXX`
    	--[createTable] Currently creating table: `XXXXX_ext`
    	--[createTable] Currently creating table: `XXXXX`
    	--[createTable] Currently creating table: `XXXXX`
    	--[createTable] Currently creating table: `XXXXX`
    	--[createTable] Currently creating table: `XXXXX`
    	--[createTable] Table "finwms"."XXXXX" is created...
    	--[populateTable] Currently populating table: `XXXXX`
    	--[createTable] Table "finwms"."XXXXX" is created...
    	--[populateTable] Currently populating table: `XXXXX`
    	--[createTable] Table "finwms"."XXXXX" is created...
    	--[populateTable] Currently populating table: `XXXXX`
    	--[createTable] Table "finwms"."XXXXX" is created...
    	--[populateTable] Currently populating table: `XXXXX`
    	--[createTable] Table "finwms"."XXXXX_ext" is created...
    	--[populateTable] Currently populating table: `XXXXX_ext`
    	--[populateTable] Total rows to insert into "finwms"."XXXXX": 9346812
    	--[populateTable] Total rows to insert into "finwms"."XXXXX": 6333907
    	--[createTable] Table "finwms"."XXXXX" is created...
    	--[populateTable] Currently populating table: `XXXXX`
    	--[populateTable] Total rows to insert into "finwms"."XXXXX": 2765754
    	--[populateTable] Total rows to insert into "finwms"."XXXXX": 6757637
    	--[populateTable] Total rows to insert into "finwms"."XXXXX_ext": 10029612
    	--[populateTableWorker]  For now inserted: 0 rows, Total rows to insert into "finwms"."XXXXX": 9346812
    
    <--- Last few GCs --->
    
      360175 ms: Scavenge 2055.3 (2116.3) -> 2055.3 (2116.3) MB, 27.5 / 0 ms (+ 1.1 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
      362097 ms: Mark-sweep 2055.3 (2116.3) -> 2055.3 (2116.3) MB, 1921.9 / 0 ms (+ 1.1 ms in 1 steps since start of marking, biggest step 1.1 ms) [last resort gc].
      364010 ms: Mark-sweep 2055.3 (2116.3) -> 2055.9 (2116.3) MB, 1913.5 / 0 ms [last resort gc].
    
    
    <--- JS stacktrace --->
    
    ==== JS stack trace =========================================
    
    Security context: 0x1dcab88e3ac1 <JS Object>
        1: dispense [/home/XXXXX/src/nmig/node_modules/generic-pool/lib/generic-pool.js:~232] [pc=0x3cfdef5f5876] (this=0x27cf8c90bb51 <JS Global Object>)
        2: connect [/home/XXXXX/src/nmig/node_modules/pg/lib/pool.js:~74] [pc=0x3cfdef71e8f0] (this=0x3fb84184f939 <an Object with map 0x13ce97241611>,cb=0x137b3d98d821 <JS Function (SharedFunctionInfo 0x360dd3ef88a9)>)
        3: connect [/home/XXXXX...
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
    Aborted

**Comment by AnatolyUss** [comment]
Unfortunately, I don't have an immediate solution.
Try <a href="https://github.com/AnatolyUss/FromMySqlToPostgreSql">FromMySqlToPostgreSql</a>

**Comment by AnatolyUss** [comment]
Hi,
I've made a few changes, that improved memory consumption.
If it's still relevant, redownload the nmig package, and run it with following command 
<code>$ node --max-old-space-size=2048 --expose-gc main.js</code>
Please, let me know if it helped.

**Comment by emailgregn** [comment]
Thank you. 
Unfortunately no luck.


    $ node --max-old-space-size=2048 --expose-gc main.js
    
    	NMIG - the database migration tool
    	Copyright 2016 Anatoly Khaytovich <anatolyuss@gmail.com>
    
    	--[boot] Boot...
    	--[readDataTypesMap] Data Types Map is loaded...
    	--[boot] Boot is accomplished...
    	--[createLogsDirectory] Creating logs directory...
    	--[createLogsDirectory] Logs directory is created...
    	--[createTemporaryDirectory] Creating temporary directory...
    	--[createTemporaryDirectory] Temporary directory is created...
    	--[loadStructureToMigrate] Source DB structure is loaded...
    	--[loadStructureToMigrate] Tables to migrate: 6
    	--[loadStructureToMigrate] Views to migrate: 0
    	--[createTable] Currently creating table: `XXXXXD`
    	--[createTable] Currently creating table: `XXXXXD_ext`
    	--[createTable] Currently creating table: `XXXXXE`
    	--[createTable] Currently creating table: `XXXXXC`
    	--[createTable] Currently creating table: `XXXXXB`
    	--[createTable] Currently creating table: `XXXXXA`
    	--[createTable] Table "finwms"."XXXXXD" is created...
    	--[populateTable] Currently populating table: `XXXXXD`
    	--[createTable] Table "finwms"."XXXXXC" is created...
    	--[populateTable] Currently populating table: `XXXXXC`
    	--[createTable] Table "finwms"."XXXXXD_ext" is created...
    	--[populateTable] Currently populating table: `XXXXXD_ext`
    	--[createTable] Table "finwms"."XXXXXA" is created...
    	--[populateTable] Currently populating table: `XXXXXA`
    	--[populateTable] Total rows to insert into "finwms"."XXXXXD": 9397957
    	--[createTable] Table "finwms"."XXXXXB" is created...
    	--[populateTable] Currently populating table: `XXXXXB`
    	--[createTable] Table "finwms"."XXXXXE" is created...
    	--[populateTable] Currently populating table: `XXXXXE`
    	--[populateTable] Total rows to insert into "finwms"."XXXXXC": 6357172
    	--[populateTable] Total rows to insert into "finwms"."XXXXXA": 2781790
    	--[populateTable] Total rows to insert into "finwms"."XXXXXD_ext": 10084134
    	--[populateTableWorker]  For now inserted: 0 rows, Total rows to insert into "finwms"."XXXXXD": 9397957
    
    <--- Last few GCs --->
    
      377463 ms: Scavenge 2056.3 (2116.2) -> 2056.3 (2116.2) MB, 28.4 / 0 ms (+ 215.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
      379323 ms: Mark-sweep 2056.3 (2116.2) -> 2056.0 (2116.2) MB, 1860.0 / 0 ms (+ 545.5 ms in 14 steps since start of marking, biggest step 215.0 ms) [last resort gc].
      381180 ms: Mark-sweep 2056.0 (2116.2) -> 2056.5 (2116.2) MB, 1856.7 / 0 ms [last resort gc].
    
    
    <--- JS stacktrace --->
    
    ==== JS stack trace =========================================
    
    Security context: 0x25e535ee3ac1 <JS Object>
        1: dispense [/home/XXXXX001/src/nmig/node_modules/generic-pool/lib/generic-pool.js:~232] [pc=0x2877eda7b396] (this=0x2e6b5640bdc9 <JS Global Object>)
        2: connect [/home/XXXXX001/src/nmig/node_modules/pg/lib/pool.js:~74] [pc=0x2877eda06eb0] (this=0x2f994d351431 <an Object with map 0xb2ca33416c1>,cb=0x395ab72c6021 <JS Function (SharedFunctionInfo 0x2a8662df2949)>)
        3: connect [/home/XXXXX0...
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
    Aborted

**Comment by AnatolyUss** [comment]
This is the output for <code>$ node --max-old-space-size=2048 --expose-gc main.js</code>, 
with "data_chunk_size" : 1 ?
BTW, what values do you use at "max_pool_size_source" and "max_pool_size_target"?

**Comment by emailgregn** [comment]
yes, command as requested, data_chunk_size = 12 and max_pool values both unchanged at 10.

**Comment by emailgregn** [comment]
I see a lot (28974) of error messages in the log file of the big table.

            --[populateTableByInsert] INSERT failed...
        error: insufficient data left in message

**Comment by AnatolyUss** [comment]
Hi,
I understand, that this is probably already irrelevant for you, but this issue is fixed now.
Thank you for opening this issue, it helped me a lot to make necessary improvements.
Regards

**Comment by emailgregn** [comment]
Thank you for the release. 

Unfortunately still no success...

    $ node --expose-gc main.js
    
    	NMIG - the database migration tool
    	Copyright 2016 Anatoly Khaytovich <anatolyuss@gmail.com>
    
    	--[boot] Boot...
    	--[readDataTypesMap] Data Types Map is loaded...
    	--[boot] Boot is accomplished...
    	--[createLogsDirectory] Creating logs directory...
    	--[createLogsDirectory] Logs directory already exists...
    	--[createTemporaryDirectory] Creating temporary directory...
    	--[createTemporaryDirectory] Temporary directory is created...
    	--[loadStructureToMigrate] Source DB structure is loaded...
    	--[loadStructureToMigrate] Tables to migrate: 6
    	--[loadStructureToMigrate] Views to migrate: 1
    	--[createTable] Currently creating table: `aaabbbccc`
    	--[createTable] Currently creating table: `aaabbbccc_ext`
    	--[createTable] Currently creating table: `dddeeefff`
    	--[createTable] Currently creating table: `ggghhhiii`
    	--[createTable] Currently creating table: `jjjkkklll`
    	--[createTable] Currently creating table: `mmmnnnooo`
    	--[createTable] Table "pppqqqrrr"."aaabbbccc" is created...
    	--[populateTable] Currently populating table: `aaabbbccc`
    	--[createTable] Table "pppqqqrrr"."mmmnnnooo" is created...
    	--[populateTable] Currently populating table: `mmmnnnooo`
    	--[createTable] Table "pppqqqrrr"."aaabbbccc_ext" is created...
    	--[populateTable] Currently populating table: `aaabbbccc_ext`
    	--[createTable] Table "pppqqqrrr"."ggghhhiii" is created...
    	--[populateTable] Currently populating table: `ggghhhiii`
    	--[createTable] Table "pppqqqrrr"."jjjkkklll" is created...
    	--[populateTable] Currently populating table: `jjjkkklll`
    	--[createTable] Table "pppqqqrrr"."dddeeefff" is created...
    	--[populateTable] Currently populating table: `dddeeefff`
    	--[populateTable] Total rows to insert into "pppqqqrrr"."aaabbbccc": 10084734
    	--[populateTable] Total rows to insert into "pppqqqrrr"."mmmnnnooo": 2966740
    	--[populateTable] Total rows to insert into "pppqqqrrr"."aaabbbccc_ext": 10816872
    	--[populateTable] Total rows to insert into "pppqqqrrr"."ggghhhiii": 6662242
    	--[populateTable] Total rows to insert into "pppqqqrrr"."jjjkkklll": 7068015
    	--[populateTable] Total rows to insert into "pppqqqrrr"."dddeeefff": 8831335
    /home/xxxyyyzzz/src/nmig/node_modules/mysql/lib/protocol/Parser.js:77
            throw err; // Rethrow non-MySQL errors
            ^
    
    TypeError: must start with number, buffer, array or string
        at fromObject (buffer.js:140:11)
        at new Buffer (buffer.js:62:10)
        at FromMySQL2PostgreSQL.boot.FromMySQL2PostgreSQL.sanitizeValue (/home/xxxyyyzzz/src/nmig/migration/fmtp/FromMySQL2PostgreSQL.js:154:22)
        at Query._callback (/home/xxxyyyzzz/src/nmig/migration/fmtp/FromMySQL2PostgreSQL.js:1055:79)
        at Query.Sequence.end (/home/xxxyyyzzz/src/nmig/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
        at Query._handleFinalResultPacket (/home/xxxyyyzzz/src/nmig/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
        at Query.EofPacket (/home/xxxyyyzzz/src/nmig/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
        at Protocol._parsePacket (/home/xxxyyyzzz/src/nmig/node_modules/mysql/lib/protocol/Protocol.js:280:23)
        at Parser.write (/home/xxxyyyzzz/src/nmig/node_modules/mysql/lib/protocol/Parser.js:73:12)
        at Protocol.write (/home/xxxyyyzzz/src/nmig/node_modules/mysql/lib/protocol/Protocol.js:39:16)
        at Socket.<anonymous> (/home/xxxyyyzzz/src/nmig/node_modules/mysql/lib/Connection.js:96:28)

**Comment by AnatolyUss** [comment]
Strange.
Could you send me mysql dump (only structure, without data), "/temporary_directory" and "/logs_directory"?
My email is <a mailto="anatolyuss@gmail.com">anatolyuss@gmail.com</a>.
Thanks

**Comment by AnatolyUss** [comment]
I've just made a new release (v1.1.1).
A part of changes in the new release addresses your issues directly.
Please, redownload an entire package (of course, if nmig is still relevant for you).
