### ISSUE TITLE
Convert tinyint(mysql) to boolean(psql)

### ISSUE THREAD

**Issue by fjfalcon** [AnatolyUss/nmig#13]
Greetings.
Returned to attemp to migrate production database from mysql to postgresql.
Founded one issue that maybe should be solved in NMIG? 

When i use mysql i use type tinyint with only two values: 0 - false, 1 - true.
But with postgresql i will need to convert all my tinyint columns to boolean... 
Maybe NMIG can convert it when migrating databases? 

p.s. i started my first project on node.js(mysql_camelcase_renamer), i hope you don't mind if i take some of your templates? 
Thank you for you software.

**Comment by AnatolyUss** [comment]
Hi Pavel,
Of course, I don't mind! My soft is your soft (GNU GPL)!
BTW, consider to visit <a href="http://learn.javascript.ru">learn.javascript.ru</a>, greatest resource to learn advanced js! 

Now, regarding the issue:
1. in MySQL, boolean is just an alias of tinyint, and tinyint can contain a lot more value than 0 or 1.
    That is why I'm not going to change the DataTypesMap.
    BUT!
2. if you are sure, that in your database tinyint is used only as boolean, then
    2.1. before running nmig, open DataTypesMap.json
    2.2. replace 
           <code>
"tinyint" : {
        "increased_size"           : "int",
        "type"                     : "smallint",
        "mySqlVarLenPgSqlFixedLen" : true
    },
</code>
    with
<code>
"tinyint" : {
        "increased_size"           : "",
        "type"                     : "boolean",
        "mySqlVarLenPgSqlFixedLen" : true
    },
</code>
Everything will work properly.
Remark: in PostgreSQL, boolean is not an alias, but a real data-type, that also accepts values like: true-false, t-f, 0-1, etc...
P.S.
Share the link to your project.
Good luck!
