### ISSUE TITLE
Name of the tables are created with double quotes

### ISSUE THREAD

**Issue by aderbas** [AnatolyUss/nmig#14]
After migration tables are created with double quotation in the name. Like this: mysql table is _foobar_ and in postgres are created "foobar". 

```
postgres> select * from foobar;
postgres> ERROR:  relation "foobar" does not exist
postgres> select * from "foobar"; 
postgres> // thats ok 
```

**Comment by AnatolyUss** [comment]
Hi,
I guess, your MySQL db has been migrated successfully, and you actually have a question regarding the "strange PostgreSQL's behavior", right?

The issue, that you have described, usually occur if foobar is "camelcased" (for example: FooBar).
In general, you should use "your_schema"."your_table" syntax to reference a table in a query.

**Comment by aderbas** [comment]
I do not know why, in the line that creates the table removed the double quotes:
https://github.com/AnatolyUss/nmig/blob/master/migration/fmtp/FromMySQL2PostgreSQL.js#L871
I changed
```
'CREATE TABLE "' + self._schema + '"."' + self._clonedSelfTableName + '".......
```
to
```
'CREATE TABLE ' + self._schema + '.' + self._clonedSelfTableName + '.......
```
And now all table created without double quotes

**Comment by AnatolyUss** [comment]
You should not.
If table name will be camelcased, then such change will lead to problems.

I would recommend you to read about major differences between MySQL and
PostgreSQL.

**Comment by aderbas** [comment]
I understand, I read about it. After I did the migration I'm back to the original code. =D
