### ISSUE TITLE
No permissions

### ISSUE THREAD

**Issue by jeanCarloMachado** [AnatolyUss/nmig#15]
I'm getting this error:
``` 
SQL: COPY "test_schema"."FiscalNCM" FROM '/root/nmig/temporary_directory/FiscalNCM7248.csv' DELIMITER ',' CSV;

        --[populateTableWorker] error: could not open file "/root/nmig/temporary_directory/FiscalTipoProduto0.csv" for reading: Permission denied
```

But I'm running the script as root so it should not be a problem.

**Comment by AnatolyUss** [comment]
Did you install nmig at the same machine where your PostgreSQL running?

During migration nmig creates temporary files, which MUST be accessible for your PostgreSQL.
That's why nmig should be installed at the same machine, where your PostgreSQL runs.

**Comment by poppingtonic** [comment]
@AnatolyUss Hi, thanks for this awesome tool! 
I have the same error, here's my `errors-only.log` file:
[errors-only.txt](https://github.com/AnatolyUss/nmig/files/563946/errors-only.txt)
