### ISSUE TITLE
empty string interpreted as NULL

### ISSUE THREAD

**Issue by dangogh** [AnatolyUss/nmig#17]
Using the latest rev today (de78b97fa38f56fe4ad2e73c4fb9b194392745ed).

I have a NOT NULL column in a table,  but empty string in one place.  I see this error during the translation:

```
	--[processNull] Error while setting NULL for "test_schema"."location"."address"...
error: column "address" contains null values
```

```
mysql> select * from location where address is null;
Empty set (0.00 sec)
mysql> select * from location where address = '';
+-----+------+------------+-----------------------------+
| id  | name | address     | last_updated              |
+-----+------+------------+-----------------------------+
| 241 | me  |                | 2015-04-06 11:51:09 |
+-----+------+------------+-----------------------------+
1 row in set (0.00 sec)
```

**Comment by dangogh** [comment]
realized that isn't really the issue.   This column is not "NOT NULL".  I'm closing this and opening a new issue to describe it more accurately.

**Comment by dangogh** [comment]
created a small test case -- that really was the issue.   SQL to reproduce:
```
use t;

CREATE TABLE `location` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `address` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO `location` VALUES (1,'myself','');
```

and here's the error I receive:
```
	--[processNull] Error while setting NULL for "test_schema"."location"."address"...
error: column "address" contains null values


	SQL: ALTER TABLE "test_schema"."location" ALTER COLUMN "address" SET NOT NULL;

````

**Comment by AnatolyUss** [comment]
Try to run 
<code>ALTER TABLE "test_schema"."location" ALTER COLUMN "address" SET NOT NULL;</code>
manually, and tell me if the constrain was created.
Thanks.

**Comment by dangogh** [comment]
I get this error:
```
t=# ALTER TABLE "test_schema"."location" ALTER COLUMN "address" SET NOT NULL;
ERROR:  column "address" contains null values
```

**Comment by dangogh** [comment]
Looks like I'm able to work around this by modifying mysql db to allow null in those columns prior to the conversion.   That should be ok for my conversion experiments,  but it would be nice for it to handle this case without intervention: `alter table location modify column address varchar(128) null;`

**Comment by AnatolyUss** [comment]
nmig creates a few temporary .csv files during execution, and PostgreSQL is probably struggling to distinguish between NULL and an empty string when reading those files.

**Comment by domino14** [comment]
Anyone know any workarounds for this issue?

**Comment by AnatolyUss** [comment]
Yes, you're right.
Unfortunately, I didn't find any reliable workaround...
This is a "known issue".

**Comment by AnatolyUss** [comment]
Just added this issue to KNOWN ISSUES section in README.md

**Comment by dangogh** [comment]
thanks..   I'm good with that...
