### ISSUE TITLE
Issues with blob columns not getting converted propertly

### ISSUE THREAD

**Issue by webm0nk3y** [AnatolyUss/nmig#18]
I have an application with encrypted data stored in blob columns. When converting to postgres, it put the data in bytea columns, but doesn't seem to have converted the data properly.

I noticed that if I used the --hex-blob option when dumping with mysqldump and then use decode(..., 'hex') when importing the value, it worked.

For example:
```
mysqldump -u root -p --skip-quote-names --hex-blob --skip-triggers --compact --no-create-info <mydb> <my table> | sed "s/0x\([0-9A-F]*\)/decode('\1','hex')/g"
```

**Comment by AnatolyUss** [comment]
Hi,
Sorry for the delay.
When some kind of binary or blob column detected, nmig HEX(`your_column`)  and then loads the value into PostgreSQL.
How exactly have you tried to retrieve data (bytea) from PostgreSQL?
PostgreSQL has DECODE() function, have you tried to use it?
