### ISSUE TITLE
Large datasets not converting

### ISSUE THREAD

**Issue by mikebronner** [AnatolyUss/nmig#19]
I'm getting HUGE error logs consisting of entries like this:

```
        SQL: COPY "public"."carets_media_prop_media" FROM '/Users/mike/Developer/nmig/temporary_directory/carets_media_prop_media3923640.csv' DELIMITER ',' CSV;

        --[populateTableWorker] error: could not open file "/Users/mike/Developer/nmig/temporary_directory/carets_media_prop_media3933720.csv" for reading: No such file or directory


        SQL: COPY "public"."carets_media_prop_media" FROM '/Users/mike/Developer/nmig/temporary_directory/carets_media_prop_media3933720.csv' DELIMITER ',' CSV;

        --[populateTableWorker] error: could not open file "/Users/mike/Developer/nmig/temporary_directory/carets_media_prop_media3936240.csv" for reading: No such file or directory
```

Any idea how to fix this? I have attempted 3 times now to convert a database from MySQL to Postgres and always ran into these errors, which eventually caused the conversion process to grind to a halt.

**Comment by AnatolyUss** [comment]
Hi,
nmig should reside in the file-system where it "visible" from PostgreSQL point of view.
Preferebly, nmig should reside on the same machine, where PostgreSQL installed.

**Comment by mikebronner** [comment]
That's the ticket! Thanks, chugging along nicely now. :) Perhaps this could be added more prominently to the README as a requirement to have the scripts accessible by the PSQL instance data is being imported to?

Thanks again for all you hard work on this. It's saving me countless hours!
