### ISSUE TITLE
Convert redmine database fails

### ISSUE THREAD

**Issue by movcale** [AnatolyUss/nmig#20]
Trying to convert redmine database using nmig tool.

Seems that all datetime columns can not be handled.
For example I`ve got:

```
    --[populateTableByInsert] INSERT failed...
```

error: incorrect binary data format in bind parameter 6

```
    SQL: INSERT INTO "redmine_production"."custom_values" VALUES($1,$2,$3,$4,$5,$6);
```

This is one line from custom_values214008.csv:
478524,Issue,27462,4,Val1,"{""type"":""Buffer"",""data"":[50,48,49,54,45,48,53,45,48,52,32,48,57,58,51,53,58,48,56]}"

This is mysql table:
mysql> desc custom_values;
+-----------------+-------------+------+-----+---------+----------------+
| Field           | Type        | Null | Key | Default | Extra          |
+-----------------+-------------+------+-----+---------+----------------+
| id              | int(11)     | NO   | PRI | NULL    | auto_increment |
| customized_type | varchar(30) | NO   | MUL |         |                |
| customized_id   | int(11)     | NO   |     | 0       |                |
| custom_field_id | int(11)     | NO   | MUL | 0       |                |
| value           | text        | YES  |     | NULL    |                |
| updated_on      | datetime    | YES  |     | NULL    |                |
+-----------------+-------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)

mysql> select \* from custom_values where id=478524;
+--------+-----------------+---------------+-----------------+-------+---------------------+
| id     | customized_type | customized_id | custom_field_id | value | updated_on          |
+--------+-----------------+---------------+-----------------+-------+---------------------+
| 478524 | Issue           |         27462 |               4 | Val1    | 2016-05-04 09:35:08 |
+--------+-----------------+---------------+-----------------+-------+---------------------+
1 row in set (0.00 sec)

Also trying to set different datestyle in new postgres database:
ALTER DATABASE redmine_production SET datestyle = 'ISO, YMD';
or
ALTER DATABASE redmine_production SET datestyle = 'ISO, DMY';
but have no success with the same error.

**Comment by AnatolyUss** [comment]
Hi,
Migration of datetime columns is supported.
What version of MySQL do you use?
Please, send me the "/errors-only.log" file.

**Comment by movcale** [comment]
Hi,

$mysql --version
mysql  Ver 14.14 Distrib 5.1.72, for debian-linux-gnu (x86_64) using readline 6.1

I manage to convert this database with yours FromMySqlToPostgreSql utility

**Comment by AnatolyUss** [comment]
Should be fixed now.
