### ISSUE TITLE
Tables containing a field of type `point` are not copied

### ISSUE THREAD

**Issue by benharold** [AnatolyUss/nmig#21]
I'm attempting to migrate a database from MySQL 5.5 to Postgres 9.5. Everything works great except for tables that include spatial data in the form of a `point` type field.

I checked `logs_directory/errors-only.log` and found several errors similar to this:

```
--[populateTableWorker] Error: ER_SP_DOES_NOT_EXIST: FUNCTION database_name.ST_AsWKB does not exist

SQL: SELECT `id`,`lr_id`,`parcel`,`street_num`,`street_dir`,`street_name`,`city`,`zip`,HEX(ST_AsWKB(`coords`)),`created_at`,`updated_at` FROM `lr_address` LIMIT 0,486;
```

The query works fine if I input it directly into MySQL, but for some reason it does not work in the `nmig` script.

**Comment by AnatolyUss** [comment]
Strange.
Could you send me the <code>logs_directory/errors-only.log</code>(zipped)?

**Comment by benharold** [comment]
Here it is: [errors-only.tar.gz](https://github.com/AnatolyUss/nmig/files/325806/errors-only.tar.gz)

**Comment by benharold** [comment]
I just installed version 2.11.1 of the node mysql module that you're using and I got the same error when I ran one of the offending queries directly, so I'm going to look a bit further into it. Could be a driver maybe.

**Comment by benharold** [comment]
The ST_AsWKB function works with MariaDB 10.1.14 but does not work with MySQL 5.5.13. I changed `./migration/fmtp/ColumnsDataArranger.js:40` from `HEX(ST_AsWKB())` to `HEX(AsBinary())`, which manages to pull the data out of the table, but then the insert fails:

    --[populateTableByInsert] INSERT failed...
    error: invalid input syntax for type point: "01010000007A8CF2CCCBE34340A088450C3B8D55C0"

**Comment by benharold** [comment]
According to [the MySQL website](https://dev.mysql.com/doc/refman/5.6/en/gis-format-conversion-functions.html#function_st-asbinary):

> ST_AsBinary() and ST_AsWKB() were added in MySQL 5.6.1.

and

> ST_AsBinary(), ST_AsWKB(), AsBinary(), and AsWKB() are synonyms.

so `AsWKB` or `AsBinary` would probably be a better choice as it supports MySQL pre 5.6

**Comment by AnatolyUss** [comment]
Fixed.<br>
Please, download version <code>2.4.0</code>, if it is relevant.
