### ISSUE TITLE
Timestamp import problem

### ISSUE THREAD

**Issue by jakobc** [AnatolyUss/nmig#22]
When I ran this, it refused to transfer any tables with timestamp data.

I found out that the IF-function used to fetch dates from MySQL prevents the node mysql module from returning timestamps as dates. Instead of dates, they will return a Buffer, which will not be imported from the CSV.
E.g. the query 
`select IF(cs_timestamp IN('0000-00-00', '0000-00-00 00:00:00'), '-INFINITY', cs_timestamp) from cs where id=1`
returns a binary (buffer), but the query
`select cs_timestamp from cs where id=1`
returns a Date object.
I simply commented out the timestamp clause in ColumnsDataArranger.js, and it worked fine.
Maybe there is a better way to handle zero dates?
This was with version 2.11.1 of mysql.

Great tool, BTW!

**Comment by AnatolyUss** [comment]
Hi and thanks for your feedback!
Honestly, I'm pretty sure, this is the best way to handle zero dates...
But, if you have a better idea, please, share with me!

**Comment by jakobc** [comment]
I agree, the problem is that the node MySQL reads it as a blob. Adding a cast will work better (e.g. adding cast(`<column>` as char) in the ColumnsData.
            strRetVal += 'IF(`' + arrTableColumns[i].Field
                      +  '` IN(\'0000-00-00\', \'0000-00-00 00:00:00\'), \'-INFINITY\', cast(`'
                      +  arrTableColumns[i].Field + '` as char)),';*/

Do you want me to make a pull request?

**Comment by AnatolyUss** [comment]
Just merged the changes.
Thanks!

**Comment by jakobc** [comment]
Cool, I've been using this for 3 quite big DBs now!
