### ISSUE TITLE
TypeError: Cannot read property 'rowCount' of undefined

### ISSUE THREAD

**Issue by mikebronner** [AnatolyUss/nmig#25]
I started getting this error after a large table with 1.7 million rows completed transferring. Any ideas what might be causing this?

```
	--[readDataPool] Data-Pool is loaded...
	--[loadData] Loading the data...
/home/forge/nmig/migration/fmtp/DataLoader.js:173
                                                                        if (isIntNumeric(result.rowCount)) {
                                                                                               ^

TypeError: Cannot read property 'rowCount' of undefined
    at /home/forge/nmig/migration/fmtp/DataLoader.js:173:96
    at null.callback (/home/forge/nmig/migration/fmtp/DataLoader.js:89:16)
    at Query.handleError (/home/forge/nmig/node_modules/pg/lib/query.js:131:17)
    at null.<anonymous> (/home/forge/nmig/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at Socket.<anonymous> (/home/forge/nmig/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

**Update:** It was trying to read a table that I had renamed after interrupting the migration. I couldn't figure out how to remove the old table name from the migration list. Is there a way to do that?

**Comment by greshnik** [comment]
Migrator use COPY from csv for import data to postgres. If this request return error you get this error. In my pull request add output sql error message.

**Comment by mikebronner** [comment]
I re-ran the entire migration from scratch, deleting all the tables in the target postgres database, and got this error after many hours of running:

```
	--[loadData] Loading the data...
	--[dataPipe]  For now inserted: 186 rows, Total rows to insert into "public"."users": 186
	--[dataPipe]  For now inserted: 74648 rows, Total rows to insert into "public"."mls_user_listing_status": 117120
/home/forge/nmig/migration/fmtp/DataLoader.js:173
                                                                        if (isIntNumeric(result.rowCount)) {
                                                                                               ^

TypeError: Cannot read property 'rowCount' of undefined
    at /home/forge/nmig/migration/fmtp/DataLoader.js:173:96
    at null.callback (/home/forge/nmig/migration/fmtp/DataLoader.js:89:16)
    at Query.handleError (/home/forge/nmig/node_modules/pg/lib/query.js:131:17)
    at null.<anonymous> (/home/forge/nmig/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at Socket.<anonymous> (/home/forge/nmig/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

The errors_only.log file reports this:

```
       --[populateTableWorker] Error: ER_NO_SUCH_TABLE: Table 'investorexperts.tblCompsAnalysis' doesn't exist

        SQL: SELECT `step`,`beds`,`baths`,`livingsf`,`age`,`distance`,`lotsf` FROM `tblCompsAnalysis` LIMIT 0,126;
```
This table does not exist in my source mysql database (it used to, but I removed it prior to this migration). This brings me to my question from the original post: how can I completely reset tables for nmig? It seems to cache them somewhere once I run it.

**Comment by AnatolyUss** [comment]
Hello,
Here are 3 steps to make:
1.
Explore your target PostgreSQL database. It should be completly empty. If
you'll find there some tables, views or sequences - drop them.
2.
Explore the nmig directory. If you'll see there "temporary_directory" or
"logs_directory" - remove them.
3.
Now you can restart the nmig.

**Comment by mikebronner** [comment]
@AnatolyUss I did that, but it didn't help. Where is the list of tables that needs to be converted stored, so I can edit that? I REALLY don't want to start over and have this run for another 12 hours

**Comment by mikebronner** [comment]
I started over from scratch, and the error occurred again. Unfortunately the `errors_only.log` has no entries, and the output is as follows:

```
	--[dataPipe]  For now inserted: 1277374 rows, Total rows to insert into "public"."carets_property_res": 1761659
	--[loadData] Loading the data...
	--[dataPipe]  For now inserted: 788 rows, Total rows to insert into "public"."tbllookupzip": 788
/home/forge/nmig/migration/fmtp/DataLoader.js:173
                                                                        if (isIntNumeric(result.rowCount)) {
                                                                                               ^

TypeError: Cannot read property 'rowCount' of undefined
    at /home/forge/nmig/migration/fmtp/DataLoader.js:173:96
    at null.callback (/home/forge/nmig/migration/fmtp/DataLoader.js:89:16)
    at Query.handleError (/home/forge/nmig/node_modules/pg/lib/query.js:131:17)
    at null.<anonymous> (/home/forge/nmig/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at Socket.<anonymous> (/home/forge/nmig/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
```

**Comment by AnatolyUss** [comment]
I'll check the issue a.s.a.p.
Sorry...

**Comment by twistedR** [comment]
I ran into the same issue. Converting my postgres user to a superuser fixed the issue. 

So in postgres do `alter user username with superuser`. Then recreate an empty database and run `node nmig.js`.

**Comment by mikebronner** [comment]
hi @twistedR , thanks for the proposed work-around. Unfortunately the user I am using is already a superuser. I checked using the following query:

```sql
select usesuper from pg_user where usename = CURRENT_USER;
```

**Comment by AnatolyUss** [comment]
Hello,
I've released a new version of node (v2.1.0).
Your issue is solved.
Try latest nmig v2.1.0 (if it's still relevant).

**Comment by mikebronner** [comment]
@AnatolyUss thanks for fixing that. I'm not sure if I will be able to try it out, as the project I was migrating is almost done (I ended up writing my own migration scripts in PHP). Thanks for all your efforts in this, though! :)

**Comment by kwe** [comment]
@AnatolyUss new version worked for me - many thanks

**Comment by AnatolyUss** [comment]
I'm glad to help!

2016-08-24 2:23 GMT+03:00 kwe <notifications@github.com>:
