### ISSUE TITLE
Error "const fs = require('fs');

### ISSUE THREAD

**Issue by mpenguin** [AnatolyUss/nmig#27]
I'm on Ubuntu Server 14.04 and attempting to use NMIG. I have config.json properly configured, but when I run

`nodejs nmig.js` (I should be using this instead of using 'node' because of a package conflict on Ubuntu, right?

I get the following output:

```
/home/ryan/nmig/nmig.js:23
const fs   = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Any idea on how to resolve this issue?

**Comment by AnatolyUss** [comment]
What version of node do you use?
Should be node >= 5

**Comment by mpenguin** [comment]
`node -v`
gives me
`v6.3.1`
`nodejs -v`
gives me
`v0.10.25`

After following instructions to update to the latest version, I tried again using
`node nmig.js`
and got the following:
```
NMIG - the database migration tool
Copyright 2016 Anatoly Khaytovich <anatolyuss@gmail.com>
Boot...
--[readDataTypesMap] Data Types Map is loaded...
--[createLogsDirectory] Creating logs directory...
--[createLogsDirectory] Logs directory already exists...
--[createTemporaryDirectory] Creating temporary directory...
--[createTemporaryDirectory] Temporary directory is created...
--[cleanup] Cleanup resources...
--[removeTemporaryDirectory] TemporaryDirectory located at "/home/ryan/nmig/temporary_directory" is removed
--[closeConnections] All DB connections to both MySQL and PostgreSQL servers have been closed...
--[cleanup] Cleanup finished...
--[cleanup] Cleanup resources...
--[removeTemporaryDirectory] Note, TemporaryDirectory located at "/home/ryan/nmig/temporary_directory" is not removed
--[removeTemporaryDirectory] Error: ENOENT: no such file or directory, scandir '/home/ryan/nmig/temporary_directory'
--[closeConnections] All DB connections to both MySQL and PostgreSQL servers have been closed...
--[cleanup] Cleanup finished...
--[cleanup] Cleanup resources...
--[removeTemporaryDirectory] Note, TemporaryDirectory located at "/home/ryan/nmig/temporary_directory" is not removed
--[removeTemporaryDirectory] Error: ENOENT: no such file or directory, scandir '/home/ryan/nmig/temporary_directory'
--[closeConnections] All DB connections to both MySQL and PostgreSQL servers have been closed...
--[cleanup] Cleanup finished...
```
So it seems like it worked, yeah?

**Comment by AnatolyUss** [comment]
No, it didn't.
Please, follow this steps:
1. Remove your old node installation.
2. Install the latest node.
3. Install the latest nmig (v2.1.0).
4. Create a new database (it should be empty).
5. Run nmig.

**Comment by rayfun** [comment]
Same here. Did the above steps.

axel@iris:~/db/nmig$ node nmig.js 

	NMIG - the database migration tool
	Copyright 2016 Anatoly Khaytovich <anatolyuss@gmail.com>
	 Boot...
	--[readDataTypesMap] Data Types Map is loaded...
	--[createLogsDirectory] Creating logs directory...
	--[createLogsDirectory] Logs directory is created...
	--[createTemporaryDirectory] Creating temporary directory...
	--[createTemporaryDirectory] Temporary directory is created...
	--[createStateLogsTable] table "public"."state_logs_publicmail" is created...
	--[createDataPoolTable] table "public"."data_pool_publicmail" is created...
	--[cleanup] Cleanup resources...
	--[removeTemporaryDirectory] TemporaryDirectory located at "/home/axel/db/nmig/temporary_directory" is removed
	--[closeConnections] All DB connections to both MySQL and PostgreSQL servers have been closed...
	--[cleanup] Cleanup finished...
	--[dropDataPoolTable] table "public"."data_pool_publicmail" is dropped...
	--[dropStateLogsTable] table "public"."state_logs_publicmail" is dropped...
	--[cleanup] Cleanup resources...
	--[removeTemporaryDirectory] Note, TemporaryDirectory located at "/home/axel/db/nmig/temporary_directory" is not removed 
	--[removeTemporaryDirectory] Error: ENOENT: no such file or directory, scandir '/home/axel/db/nmig/temporary_directory'
	--[closeConnections] All DB connections to both MySQL and PostgreSQL servers have been closed...
	--[cleanup] Cleanup finished...
	--[generateReport] NMIG migration is accomplished.
	--[generateReport] Total time: 00:00:00
	--[generateReport] (hours:minutes:seconds)
axel@iris:~/db/nmig$ nodejs -v
v6.5.0
