### ISSUE TITLE
Migrating views

### ISSUE THREAD

**Issue by acosonic** [AnatolyUss/nmig#32]
Only one view was migrated which didn't have back-ticks \` like standard mysql practice....

For example:

select \`packages\`.\`shipment_id\` AS \`shipment_id\`,group_concat(\`packages\`.\`tracking_number\` separator ', ') AS \`tracking_numbers\`,sum(\`packages\`.\`insurance_amount\`) AS \`insurance_amount\`,sum(\`packages\`.\`weight\`) AS \`weight\`,sum(\`packages\`.\`cod_amount\`) AS \`cod_amount\` from \`packages\` group by \`packages\`.\`shipment_id\`

Also notice the function replacement that needs to be done as well...

**Comment by AnatolyUss** [comment]
Hello and sorry for the late response,
Views migration is supported at basic level only.
All views (the SQL script, that was rejected by PostgreSQL), that were not migrated can be found under <code>/nmig/logs_directory/not_created_views</code>.
You will see each SQL (view) script in separate file.
Probably, you will need to fix those scripts manually...
Supporting <b>precise</b> migration of views may require implementing a full SQL parser.
While it is possible, currently I don't have enough spare time for such an improvement.

Thank you for your feedback!
