### ISSUE TITLE
Config option to skip schema migration?

### ISSUE THREAD

**Issue by mltsy** [AnatolyUss/nmig#34]
I used this to migrate a database created with Rails' ActiveRecord, which tracks the Schema for me.  ActiveRecord did a better job of setting up the schema properly in Postgres, due to it's better knowledge of the context.  It would be great to be able to skip NMIG's schema migration, and just migrate data into a preset schema.  (Is there any way to do that?)

**Comment by mltsy** [comment]
P.S. THANK you for creating this amazing tool that actually works! ;)

**Comment by AnatolyUss** [comment]
No problem, I'll implement it asap (probably this weekend).
Thanks for the feedback!

**Comment by AnatolyUss** [comment]
Recently I've released a new version (2.2.0). 
There you have a config option "migrate_only_data".
In order to skip schema migration - simply set "migrate_only_data" : true

**Comment by mltsy** [comment]
Amazing!  Thank you :+1:

**Comment by mltsy** [comment]
Now... just to make sure I'm doing this right - is there a preferred way to upgrade a Node app?  Or can I just run `git pull` and `npm install` again?
