### ISSUE TITLE
Migrating autoincrement/sequence values

### ISSUE THREAD

**Issue by mltsy** [AnatolyUss/nmig#35]
I noticed when migrating my database that even though NMIG was able to create the correct sequences for each table, it didn't set the values for any of them... is there some reason they can't be set (or is there a way to set them)?  Getting MySQL's auto_increment value for a table should be a simple enough query:

``` sql
SELECT `AUTO_INCREMENT` FROM  INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'DatabaseName' AND   TABLE_NAME   = 'TableName';
```

**Comment by mltsy** [comment]
Incidentally, it would be great if this feature to migrate sequence data would still function, even when schema migrations are skipped, as in #34 (although I could see them being related)

**Comment by SGobeil** [comment]
This would be great addition to this great tool.

**Comment by AnatolyUss** [comment]
> NMIG was able to create the correct sequences for each table, it didn't set the values for any of them...

What exactly do you mean?
Here is a sample sequence:
<code>
CREATE SEQUENCE public.xxx_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 627
  CACHE 1;
ALTER TABLE public.xxx_id_seq
  OWNER TO postgres;
</code>
The <code>START</code> property is set to the max id of <code>public.xxx</code> table...
Am I missing something?

**Comment by mltsy** [comment]
Oh!  Huh... I will try to investigate.  For some reason all my sequences have no start value after migrating:

```
db# SELECT currval('clients_id_seq');
ERROR:  currval of sequence "clients_id_seq" is not yet defined in this session
```

**Comment by mltsy** [comment]
Ooooh, it doesn't set the _current_ value, but if I call `nextval` it works as expected... well now I have to go back to the reason I thought it was broken in the first place, which was some Rails error about a duplicate primary key if I'm not mistaken...  Wow!  That would be great if it was just a misleading error and it works fine now, hah. :laughing: 

I'll let you know :blush:

**Comment by AnatolyUss** [comment]
Joe,
I made a mistake.
When migrating only data (when a schema is preset) no sequences got updated.
I'll fix it asap.

**Comment by mltsy** [comment]
Oh, hah, I was just testing to see if the sequences actually worked as expected, but yup, no sequences when I did `migrate_only_data`.  So, happy to confirm what you already knew ;)

**Comment by AnatolyUss** [comment]
The "sequences issue" is finally resolved.

**Comment by mltsy** [comment]
Ah, great news! :smile:  Thank you :bowing_man:
