### ISSUE TITLE
Permission denied for CSVs stored in temporary_directory

### ISSUE THREAD

**Issue by poppingtonic** [AnatolyUss/nmig#36]
@AnatolyUss Hi, thanks for this awesome tool! 
I have the same error as in #15 and #9, here's my `errors-only.log` file:
[errors-only.txt](https://github.com/AnatolyUss/nmig/files/563946/errors-only.txt)

Note: I've installed nmig in the same machine as PostgreSQL, and the database user in `target` is a superuser as per your suggestion in #9 .

**Comment by SGobeil** [comment]
I moved nmig folder to /tmp and it worked fine afterward...

**Comment by AnatolyUss** [comment]
Hello,
Sorry for the late response.
Recently, I've released a new version (2.2.0).
From now there is no need to:
1. worry about file system permissions.
2. install nmig on the same machine, where PostgreSQL resides.
