### ISSUE TITLE
Errors during data migration, columns aren't passed in the right order

### ISSUE THREAD

**Issue by SGobeil** [AnatolyUss/nmig#37]
While data is being copied between databases, it seems that for some tables data isn't passed in the right order from the csv files.  For example, I get this message during data transfer : 

error: invalid input syntax for integer: "Validated Data".

"Validated data" is a string content from the first column of the table named STATUS, followed by three integer.  In the corresponding csv file, three integers are passed followed by the string STATUS.

**Comment by AnatolyUss** [comment]
Hi,
I'll check it as soon as possible.

**Comment by AnatolyUss** [comment]
I can't reproduce the issue.
What was the columns order in the original MySQL table?

**Comment by SGobeil** [comment]
Sorry for the delay, I'm leaving for another job and gave the lead for this migration to a co-worker.  I'll tell him to keep you informed.

**Comment by AnatolyUss** [comment]
Never mind!
Thanks, and good luck with your new job!

**Comment by AnatolyUss** [comment]
This issue is fixed in version v3.5.0
