### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by onpaws** [AnatolyUss/nmig#38]
Hello,
Thanks for posting your work on this. Great to see a fresh take using node.js!

I just wanted to bring to your attention in case you weren't already aware;

I updated the config and ran `node nmig.js`. The log scrolled by, and I think the app worked. There were a lot of these warnings too, I think they're OK to ignore but just wanted you to know. 
`(node:16263) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

I think it's related to node 7.0, which I recently updated to.

**Comment by AnatolyUss** [comment]
These warning are related to node 7.
I work on it.
Thanks for your feedback!
