### ISSUE TITLE
Migration differences

### ISSUE THREAD

**Issue by tobymurray-nanometrics** [AnatolyUss/nmig#39]
I'll use this as a catch-all for my observations, I can break them out if you'd rather.

Using NMIG off d88d364
PostgreSQL Server 9.5.4 (I know the main page says 9.3 is supported)
MySQL 5.6.16-1~exp1

If the issue is the PostgreSQL version I can retry, I'm hoping that it isn't... 

I dumped the MySQL schema, I dumped a native PostgreSQL schema, and I dumped the schema from a MySQL -> PostgreSQL migrated result. I then compared the native PostgreSQL schema with the migrated schema with [apgdiff](http://www.apgdiff.com/). The following differences exist:

#### Indices are renamed
E.g.
In MySQL: `KEY `associations_origin_id_idx` (`origin_id`),`
In native PostgreSQL: `associations_origin_id_idx`
In migrated schema: `public_associations_origin_id0_idx`

#### Tinyint not converted to boolean
Addressed in #13 - I made the changes you suggested in the discussion (after verifying all my `tinyint`s were booleans) and it worked and preserved the values. Would be marginally nicer to have a more accessible configuration, but that's getting picky. A toggle that would allow assuming all `tinyint(1)` are boolean would work for us.

#### Boolean default values are not preserved
E.g.
In MySQL: `is_time_defined` tinyint(1) DEFAULT '0'
In native PostgreSQL: `is_time_defined boolean DEFAULT false`
In migrated schema: `is_time_defined boolean`

#### String default values are not preserved
E.g.
In MySQL: 'channel_code` varchar(3) DEFAULT '','
In native PostgreSQL: 'channel_code character varying(3) DEFAULT ''::character varying,'
In migrated schema: 'channel_code character varying(3)'

Other than that, the migration went smoothly and the output is relatively easily corrected. Any configuration options I might be missing to address the above mentioned discrepancies? The only thing (besides #13) that I changed was the `config.json`. Let me know if I can provide any more information to help flesh this out. 

Thanks a lot for this tool!

**Comment by tobymurray-nanometrics** [comment]
I'm looking at trying to address some of these differences for our own use case, as the closer the resultant diff is the better for us with this one time migration. 

For the index naming I see your comment `// "schema_idxname_{integer}_idx" - is NOT a mistake.` What's the motivation for the `{integer}` field? It looks like each index on a given table is given that incrementing `cnt`, is that to address naming collisions?

**Comment by AnatolyUss** [comment]
Hello, and sorry for the late response.

The motivation to create indexes with an {integer} part is to prevent  naming collisions, that possible in case of compound indexes.

Regarding default values for boolean columns - there is  the DataTypesMap.json, which is the configuration file for data types mapping. I don't like an idea to treat tinyint in some different way (in config.json).
I realize, that there is a problem, and I'll think how to improve default values processing.

Thanks a lot for your feedback!

**Comment by tobymurray-nanometrics** [comment]
> Regarding default values for boolean columns - there is the DataTypesMap.json, which is the configuration file for data types mapping. I don't like an idea to treat tinyint in some different way (in config.json).

Agreed, it's not ideal, but MySQL has made that decision for you - they've treated `tinyint` as two different semantic types. I think the idea @frsantos had, have a flag to treat all `tinyint(1)` as boolean is a pretty quick fix that gets most of the way there. Agreed that it doesn't fit nicely into `DataTypesMap.json` though.

> The motivation to create indexes with an {integer} part is to prevent naming collisions, that possible in case of compound indexes.

What's the rationale for prefixing with the schema name? Is there the concern of a collision even with indices included?

Are you aware of the issue with the string default values not being preserved? I looked through the code quickly and the issue didn't jump out at me, I can take another stab at it though.

**Comment by AnatolyUss** [comment]
The "tinyint to boolean default values" issue is resolved without editing config.json
Just edit the DataTypesMap.json -> tinyint section (set type boolean).

**Comment by mltsy** [comment]
In case it helps in your case @tobymurray-nanometrics: There is a [new option to migrate-only-data](https://github.com/AnatolyUss/nmig/releases/tag/v2.2.0) if you have a better way of creating the correct schema as you would like it to be created.

**Comment by tobymurray-nanometrics** [comment]
The `tinyint` to `boolean` type migration works as suggested, but what I experienced is that the default was not persisted. Am I missing something that would allow the default values to be migrated as well? 

As mentioned above, this was my experience:

> E.g.
> In MySQL: is_time_defined tinyint(1) DEFAULT '0'
> In native PostgreSQL: is_time_defined boolean DEFAULT false
> In migrated schema: is_time_defined boolean

**Comment by AnatolyUss** [comment]
Yes, you are missing the latest release (v2.3.0).
In the latest release default values are persisted, and there is NO new
config option...
