### ISSUE TITLE
Empty strings interpreted as NULL

### ISSUE THREAD

**Issue by ocharles** [AnatolyUss/nmig#4]
We have a MySQL database where some tables have the empty string as a value with a not-null constraint. `nmig` generates CSV files that don't quote the empty string, so PostgreSQL (by default) interprets these fields as null. The NOT NULL creation later fails.

**Comment by AnatolyUss** [comment]
I'll check this issue a.s.a.p. (today-tomorrow).
Thanks a lot for the feedback!

**Comment by ocharles** [comment]
No rush, thank you - great program!

**Comment by AnatolyUss** [comment]
Fixed.
Sorry for the delay...

**Comment by domino14** [comment]
This doesn't seem to have been fixed in the latest version of nmig.. are there any setting changes I need to make?
