### ISSUE TITLE
Can I use this to keep two DBs in sync?

### ISSUE THREAD

**Issue by Hoya** [AnatolyUss/nmig#41]
Hi, just one question.

After the initial migration, can I run this on a set interval to keep two databases in sync?
Will it automatically detect changes and update rows / insert new rows / delete deleted rows?

**Comment by AnatolyUss** [comment]
Currently, no.
Are you looking for some kind of replication between MySQL and Postgre?

**Comment by Hoya** [comment]
Yes, our production database is MySQL but limitations on it make it hard to run specific analytics. It would be great if there was a way to periodically (e.g. every 24 hours) keep a MySQL database and Postgres database in sync. I know there are commercial solutions out there but they are extremely expensive. Do you know any alternatives?

**Comment by AnatolyUss** [comment]
Unfortunately I don't.
Such feature would be a great enhancement for nmig.
I'll consider it for the next release.


2017-01-15 11:28 GMT+02:00 Jiho Kang <notifications@github.com>:
