### ISSUE TITLE
Delimiter configuration

### ISSUE THREAD

**Issue by lungpu** [AnatolyUss/nmig#42]
Not an actual "Issue" but it would be really useful to be able to customize the delimiter to use to make the internal csv and copy. My use case is that in the original database I had to copy there were many fields using commas inside, so using comma as a delimiter was not an option. It took me a while to realize where the issue was, and hardcoding another delimiter (';') did the job, but it would have been nice to be able to set up the delimiter in the config.json, just a suggestion.

Thanks for the amazing job with this script :)

**Comment by AnatolyUss** [comment]
I've just released v2.6.0 and it has an option to customize delimiter via config.json .
Thanks for the suggestion!
