### ISSUE TITLE
Error loading table data

### ISSUE THREAD

**Issue by annikoff** [AnatolyUss/nmig#43]
Hello.
The following error appears during migration:
```
--[populateTableWorker] Error loading table data:
SELECT `id`,`journalized_id`,`journalized_type`,`user_id`,`notes`,IF(`created_on` IN('0000-00-00', '0000-00-00 00:00:00'), '-INFINITY', CAST(`created_on` AS CHAR)),`private_notes` FROM `journals` LIMIT 11683125,31155;
```
Thank you for great tool.

**Comment by AnatolyUss** [comment]
Hello,
Please, have a look at <code>/nmig/logs_directory/errors-only.log</code>.
There you will find description of all sql-related errors.
In the worst case simply send me the <code>/nmig/logs_directory/errors-only.log</code> file (zipped).
I'll try to help.

**Comment by annikoff** [comment]
Thank you for the fast reply.
Source table has "utf8_general_ci" encoding.
There are two kinds of errors.
```
--[populateTableWorker] error: invalid byte sequence for encoding "UTF8": 0x00

SQL: COPY "public"."journals" FROM STDIN DELIMITER ',' CSV;

--[populateTableWorker] error: unquoted carriage return found in data

SQL: COPY "public"."journals" FROM STDIN DELIMITER ',' CSV;
```

**Comment by annikoff** [comment]
I found solution that works for me. Both of errors is gone. I've put this code `field = field.replace(/\u0000/g, ' ');` before of this line https://github.com/AnatolyUss/nmig/blob/master/migration/fmtp/CsvStringifyModified.js#L257

**Comment by AnatolyUss** [comment]
Thanks for posting your solution!
