### ISSUE TITLE
load too slow

### ISSUE THREAD

**Issue by scottxu** [AnatolyUss/nmig#44]
mysql database 33G, It cost 9 hours, how can I speed up? I need your help, thx!

**Comment by AnatolyUss** [comment]
How much RAM is available?
How many cores installed on your machine?

Please, send me your config.json (sensitive details may be excluded).

Thanks

**Comment by scottxu** [comment]
mac pro ,2.7 GHz Intel Core i5 ,8 GB 1867 MHz DDR3
`{
    "source_description" : [
        "Connection parameters to your MySQL database",
        "Please ensure, that you have defined all parameters properly.",
        "Ensure, that details like 'charset' are included (if necessary)."
    ],
    "source" : {
            "host"     : "localhost",
            "port"     : 3306,
            "database" : "dituwuyou",
            "charset"  : "utf8mb4",
            "user"     : "root",
            "password" : "map"
    },

    "max_pool_size_source_description" : [
        "Maximal amount of simultaneous connections to your MySQL database during migration"
    ],
    "max_pool_size_source" : 50,

    "target_description" : [
        "Connection parameters to your PostgreSQL database",
        "Please ensure, that you have defined all parameters properly.",
        "Ensure, that details like 'charset' are included (if necessary)."
    ],
    "target" : {
            "host"     : "localhost",
            "port"     : 5432,
            "database" : "dituwuyou_regions",
            "charset"  : "UTF8",
            "user"     : "postgres",
            "password" : ""
    },

    "max_pool_size_target_description" : [
        "Maximal amount of simultaneous connections to your PostgreSQL database during migration"
    ],
    "max_pool_size_target" : 50,

    "pipe_width_description" : [
        "Maximal amount of data-chunks, processed in a single 'DataPipe' iteration.",
        "Note: 'pipe_width' should not be greater than 'max_pool_size_target'."
    ],
    "pipe_width" : 100,

    "max_loader_processes_description" : [
        "Each 'DataPipe' iteration processed by a separate process (o.s. thread).",
        "max_loader_processes is a maximal amount of simultaneously running loader processes.",
        "If not supplied, then max_loader_processes will be equals to one."
    ],
    "max_loader_processes" : 1,

    "loader_max_old_space_size_description" : [
        "V8 memory limit of the loader process.",
        "Possible values are: any number, representing memory limit (in MB),",
        "or DEFAULT, representing V8 default limit for your current hardware."
    ],
    "loader_max_old_space_size" : "DEFAULT",

    "encoding_description" : [
        "JavaScript encoding type.",
        "If not supplied, then utf-8 will be used as a default."
    ],
    "encoding" : "utf8",

    "schema_description" : [
        "schema - a name of the schema, that will contain all migrated tables.",
        "If not supplied, then a new schema will be created automatically."
    ],
    "schema" : "public",

    "data_chunk_size_description" : [
        "During migration each table's data will be split into chunks of data_chunk_size (in MB).",
        "If not supplied, then 1 MB will be used as a default."
    ],
    "data_chunk_size" : 1,

    "no_vacuum_description" : [
        "PostgreSQL VACUUM reclaims storage occupied by dead tuples. VACUUM is a very time-consuming procedure.",
        "By default, VACUUM will be performed automatically after migration (recommended)",
        "This behavior can be disabled for tables, included into the list (Array) below.",
        "Table names, included into the list below should be names, you use in your source database (MySQL)."
    ],
    "no_vacuum" : [],

    "exclude_tables_description": [
        "List (Array) of tables, that will not be migrated.",
        "By default, nmig will migrate all tables."
    ],
    "exclude_tables": ["ad_regions", "ad_tongjis", "api_call_feqs", "api_call_tongjis", "api_googles", 
    "ar_internal_metadata", "attr_fields", "bcf_data", "bcf_kinds", "bcf_settings", 
    "ca_watches", "categories", "corporation_infos", "ddos", "districts", "enum_items",
    "feature_words", "fendan_companies", "fendan_daily_logs", "fendan_data", "fendan_logs",
    "fendan_maps", "fendan_quick_sort_logs", "fendan_settings", "fendan_user_maps", "fendan_users",
    "filter_items", "icons", "imgs", "line_imgs", "line_layer_styles", 
    "line_layer_users", "line_layers", "line_routes", "line_styles", "line_users",
    "lines", "map_logs", "map_settings", "map_users", "map_views", "maps",
    "marker_imgs", "marker_layer_styles", "marker_layer_users", "marker_layers",
    "marker_users", "markers", "merges", "message_actions", "messages", 
    "mobile_watches", "monitorings", "notifications", "org_logs", "org_users",
    "orgs", "plans", "prints", "region_imgs", "region_layer_styles", "region_layer_users", 
    "region_layers", "region_styles", "region_users", "replies", "reply_fields", 
    "reply_imgs", "reply_templates", "schema_migrations", "sms", "user_infos", "user_login_logs", 
    "users", "view_sources", "wqblb_logs", "xingyi_customers", "xingyi_work_orders"],

    "migrate_only_data_description" : [
        "In order to skip schema migration, and just migrate data into a preset schema",
        " - set this parameter true."
    ],
    "migrate_only_data" : false,

    "delimiter_description" : [
      "Specifies the character that separates columns within each record.",
      "This must be a single one-byte character.",
      "The default is comma."
    ],
    "delimiter" : ",",

    "enable_extra_config_description" : [
        "In order to enable the additional configuration options - set this parameter true."
    ],
    "enable_extra_config" : false
}
`

**Comment by scottxu** [comment]
![image](https://cloud.githubusercontent.com/assets/780524/23388175/95b91024-fd9b-11e6-9254-8bf2a75b7657.png)

**Comment by AnatolyUss** [comment]
Please, try:
max_pool_size_source
max_pool_size_target
pipe_width
data_chunk_size
set to something between 10 to 15 each.
Keep track on RAM usage during migration.
In case of out-of-memory (if chosen data_chunk_size is too large) don't
hasitate to simply rerun the migration.
Nmig will restart from the point it was stopped at.
