### ISSUE TITLE
Error while Migrate only data

### ISSUE THREAD

**Issue by vafrcor** [AnatolyUss/nmig#46]
```log
--[populateTableWorker] error: extra data after last expected column

SQL: COPY "public"."job_tasks" FROM STDIN DELIMITER ',' CSV;
```

Do this error message is causing data corrupted ?
Thank you for any response

**Comment by AnatolyUss** [comment]
What kind of data does <code>job_tasks</code> contain?
Probably, using <code>,</code> as a delimiter <code>COPY</code> parsed more columns than actually exists in <code>job_tasks</code> table.
Depends on a data, that you have in this table, try to change the delimiter.

**Comment by AnatolyUss** [comment]
Just forgot to mention, the delimiter should be changed via the "delimiter" config parameter
(see config.json).
