### ISSUE TITLE
Prevent converting of empty strings into NULL

### ISSUE THREAD

**Issue by annikoff** [AnatolyUss/nmig#47]
Hi.
How to prevent converting of empty strings into NULL?

**Comment by AnatolyUss** [comment]
Hi,
Unfortunately, I didn't find a reliable solution for this issue.  
It is also mentioned at "known issues" section (see README.md).

**Comment by annikoff** [comment]
My hack for this problem:
- In source database run before migration `UPDATE table_name SET field_name = 'NOTNULL' WHERE field_name = '';`
- In target database run after migration `UPDATE table_name SET field_name = '' WHERE field_name = 'NOTNULL';`
