### ISSUE TITLE
How to migrate DATETIME with Timezone

### ISSUE THREAD

**Issue by yograterol** [AnatolyUss/nmig#48]
Hi,

I'm migrating a large database from MySQL to PostgreSQL, I did that DB with Django and I've a problem when nmig import `datetime` to `timestamp without timezone` because after I get a lot of errors for that.

**Comment by AnatolyUss** [comment]
Hi Yohan,
Please, try following:
1. Open <code>data_types_map.json</code>
2. Edit the <code>datetime</code> section:
"datetime" : {
        "increased_size"           : "",
        "type"                     : "timestamp with time zone",
        "mySqlVarLenPgSqlFixedLen" : false
    },

3. Do the same modification for the <code>timestamp</code> section, if relevant.
4. Please, let me know if you experience any other issue.
