### ISSUE TITLE
MySQL/Mariab partitions have lost

### ISSUE THREAD

**Issue by jmilagroso** [AnatolyUss/nmig#53]
MySQL/Mariab partitions have lost after migration.

*Mariadb 10.0.31-MariaDB-0ubuntu0.16.04.2*
*PostgreSQL 9.5.10*

**Comment by AnatolyUss** [comment]
Hello,
Could you share more details about the issue?
Could you send me migration logs ('logs_directory', zipped)?

Thanks

**Comment by AnatolyUss** [comment]
I thoroughly checked this case and found no data loss.  
What actually happens, is that Nmig does not create "partitions" out-of-the-box.  
  
Keep in mind, that PostgreSQL has a slightly different implementation/syntax for partitions.  
For a sake of example, please, have a look in the following link:  
[How to partition existing table in postgres?](https://dba.stackexchange.com/questions/106014/how-to-partition-existing-table-in-postgres).  
  
Good luck!
