### ISSUE TITLE
 Invalid string length

### ISSUE THREAD

**Issue by fjfalcon** [AnatolyUss/nmig#6]
Greetings, recieved this stacktrace when trying to import database.

```
/var/lib/postgresql/nmig/migration/fmtp/csvStringifyModified.js:64
       return callback(null, chunks.join(''));
                                    ^

RangeError: Invalid string length
    at Array.join (native)
    at null.<anonymous> (/var/lib/postgresql/nmig/migration/fmtp/csvStringifyModified.js:64:37)
    at emitNone (events.js:85:20)
    at emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

Nodejs version: 5.7.0

There are no file errors_only.log in logs_directory. 
grep error in logs_directory also says nothing. 

Thank you.

**Comment by fjfalcon** [comment]
Maybe you can recommend tools or utils or something to check source db that can fix this? 
As i can see from strace, this exception throws when working with this database schema and about 5mln rows in it. 
```

+---------------+---------------+------+-----+---------+----------------+
| Field         | Type          | Null | Key | Default | Extra          |
+---------------+---------------+------+-----+---------+----------------+
| id            | int(11)       | NO   | PRI | NULL    | auto_increment |
| contractId    | int(11)       | NO   | MUL | NULL    |                |
| posId         | int(11)       | NO   | MUL | NULL    |                |
| projectId     | int(11)       | NO   | MUL | NULL    |                |
| employeeId    | int(11)       | NO   | MUL | NULL    |                |
| date          | datetime      | NO   | MUL | NULL    |                |
| reportDay     | int(11)       | NO   |     | NULL    |                |
| supervisorId  | int(11)       | YES  | MUL | NULL    |                |
| reportData    | mediumtext    | YES  |     | NULL    |                |
| contractTime  | int(11)       | YES  |     | 0       |                |
| estimatedTime | int(11)       | YES  |     | 0       |                |
| contractRate  | decimal(19,2) | YES  |     | 0.00    |                |
| hourlyRate    | decimal(19,2) | YES  |     | 0.00    |                |
| totalPayments | int(11)       | NO   |     | 0       |                |
| totalWorkload | int(11)       | NO   |     | 0       |                |
| coordinatorId | int(11)       | YES  | MUL | NULL    |                |
| managerId     | int(11)       | YES  | MUL | NULL    |                |
+---------------+---------------+------+-----+---------+----------------+




```

**Comment by AnatolyUss** [comment]
Hi,
I'm working to fix this issue.
Honestly, I don't think, that there is something to fix on your side.
Thanks for your feedback!

**Comment by AnatolyUss** [comment]
What value did you use in "data_chunk_size" parameter in congif.json?
Could you rerun nmig with "data_chunk_size" : 1

**Comment by fjfalcon** [comment]
Tryed with 500, 200 and 100. 
When i used patch from lsei's pull request [https://github.com/AnatolyUss/nmig/pull/8] and excluded table - all works as expected.

Currently started process with data_chunk_size: 1: 

1340262 records, only 278787 inserted for 3 hours.. Still waiting.

**Comment by AnatolyUss** [comment]
"data_chunk_size" parameter's aim is to reduce RAM consumption when dealing with relatively big tables. Rerunning with "data_chunk_size" : 1 was a general recommendation, since I don't know how much available RAM do you have (most probably you can use a value greater than 1).   

What is the total size of your database (in GB)?
Please, let me know if you will have any other issues.

**Comment by fjfalcon** [comment]
I have 79gb database and 120gb ram when trying to convert it. 
As for one table only i have 18063.89gb size. 
As for 1mb chunk size: process currently working and now at 500000.
Error was at 1100000 row afaik.

**Comment by fjfalcon** [comment]
After i used https://github.com/AnatolyUss/nmig/pull/8 and tryed to convert full database with exclude "bad" table i recieved same error with another big table (6g only, btw) but with almost 10mln records.

**Comment by fjfalcon** [comment]
yes, without --max-old-space-size app falls pretty quick. 
After 24 hours with data_chunk_size 1: only 600000 rows inserted. 
Still waiting.

**Comment by fjfalcon** [comment]
3rd day running... only 800000 rows inserted. 
Still without any issue. errors-log empty

**Comment by AnatolyUss** [comment]
Thanks for update!
Please, let me know when migration will be finished.

**Comment by fjfalcon** [comment]
After i added #10 and tryed to import only one table on normal fast server with chunk_size: 500 
 i have this info:

I added to self.log current offset so i can determine what exactly table row(or at least range of rows) throws this error.
But! 
On every psql -> drop database, create database offset was different. 

So, it's not problem with data. 
Sad.

**Comment by AnatolyUss** [comment]
How big is this table?
Will I be able to run such test on laptop with 4GB RAM and ~400GB hard drive?

**Comment by fjfalcon** [comment]
Don't know about 4gb ram, but as for this notarius bug in v8  i found many reports about ram and this error. 
I know that i already feed about 120gb ram to node.js and still can get this error.
So, i think i will modify nmig to work by table and dynamically change chunk size for every table?
With step like square(configured data chunk) ? 

Or maybe better: try { working code }
catch (RangeError.String.length .) 
reduce chunkSize, repeat, if all ok: increate in to configured value, else decrease it more, repeat.

**Comment by AnatolyUss** [comment]
No problem, feel free to modify nmig!
Adjustable chunks sounds like a good idea, but I'm not sure, that it will be easy to implement.
Are you sure, that RangeError is "catchable"?
Chunk size 1mb is probably too small, but, at least it's running without errors...

**Comment by AnatolyUss** [comment]
Hi,
I've made a few changes, that improved memory consumption.
If it's still relevant, redownload the nmig package, and run it with following command 
<code>$ node --max-old-space-size=2048 --expose-gc main.js</code>
Please, let me know if it helped.

**Comment by fjfalcon** [comment]
400mb, 16gb - range error
400mb, 2gb - memory limit
200mb, 16gb - range error
100mb, 16gb - range error, but 900k rows imported

Currently trying with 75mb chunk.

**Comment by AnatolyUss** [comment]
Cool! I'm glad, that everything is ok!
So, 80GB have been migrated in 265m33.807s, correct?

**Comment by fjfalcon** [comment]
Youp, problem solved for me.
