### ISSUE TITLE
Requesting -y option to skip the Proceed (Y/N) question

### ISSUE THREAD

**Issue by snblitz** [AnatolyUss/nmig#60]
I am currently using echo y | npm start to run the code and "skip" the Process Y/N question.
A "nice to have" would be a -y argument, but I can live with the echo y if need be.

**Comment by AnatolyUss** [comment]
Actually I prefer to leave it as it is now.
Is there any disadvantage of using <code>echo y | npm start</code>?

**Comment by snblitz** [comment]
In my experience 'echo y | npm start' is more prone to breakage over
the long run than command line arguments for this particular purpose.
However, to each his own.  -y or echo y will no be a deciding factor
in whether or not I use the application.

**Comment by AnatolyUss** [comment]
For now, I decided to leave the "Y/N" question, mainly in order to denote the mode Nmig running in (regular or recovery).
Thanks for your suggestion!
