### ISSUE TITLE
--[populateTableWorker] Error loading table data:

### ISSUE THREAD

**Issue by snblitz** [AnatolyUss/nmig#61]
What looks a little suspicious to me is the 873021 in the prepareDataChunks vs 87303 down in the LIMIT.  I can paste the SQL into the mysql database and it works as one would expect.

      --[TableProcessor::createTable] Table "v25tmp"."jos_comprofiler" is created...
      --[prepareDataChunks] Total rows to insert into "v25tmp"."jos_comprofiler": 873021
      --[populateTableWorker] Error loading table data:
       SELECT `id` AS `id`,`user_id` AS `user_id`,`firstname` AS `firstname`,`middlename` AS `middlename`,`lastname` AS `lastname`,`hits` AS `hits`,IF(`message_last_sent` IN('0000-00-00', '0000-00-00 00:00:00'), '-INFINITY', CAST(`message_last_sent` AS CHAR)) AS `message_last_sent`,`message_number_sent` AS `message_number_sent`,`avatar` AS `avatar`,`avatarapproved` AS `avatarapproved`,`approved` AS `approved`,`confirmed` AS `confirmed`,IF(`lastupdatedate` IN('0000-00-00', '0000-00-00 00:00:00'), '-INFINITY', CAST(`lastupdatedate` AS CHAR)) AS `lastupdatedate`,`registeripaddr` AS `registeripaddr`,`cbactivation` AS `cbactivation`,`banned` AS `banned`,IF(`banneddate` IN('0000-00-00', '0000-00-00 00:00:00'), '-INFINITY', CAST(`banneddate` AS CHAR)) AS `banneddate`,IF(`unbanneddate` IN('0000-00-00', '0000-00-00 00:00:00'), '-INFINITY', CAST(`unbanneddate` AS CHAR)) AS `unbanneddate`,`bannedby` AS `bannedby`,`unbannedby` AS `unbannedby`,`bannedreason` AS `bannedreason`,`acceptedterms` AS `acceptedterms`,`website` AS `website`,`location` AS `location`,`occupation` AS `occupation`,`interests` AS `interests`,`company` AS `company`,`address` AS `address`,`city` AS `city`,`state` AS `state`,`zipcode` AS `zipcode`,`country` AS `country`,`phone` AS `phone`,`fax` AS `fax`,`cb_assub` AS `cb_assub`,`cb_ossub` AS `cb_ossub` FROM `jos_comprofiler` LIMIT 0,87303;

**Comment by AnatolyUss** [comment]
Could you share with me what is the size of this table?
If yes, then following is the query to check it:
<code>SELECT (data_length / 1024 / 1024) AS size_in_mb FROM information_schema.tables WHERE table_schema = 'v25tmp' AND table_name = 'jos_comprofiler';</code>

What is the value of "config.data_chunk_size"?

**Comment by AnatolyUss** [comment]
Fixed.
