### ISSUE TITLE
Feature Request: hability to set sequence names

### ISSUE THREAD

**Issue by amatosg** [AnatolyUss/nmig#66]
it would be nice to be able to set the suffix of sequences, right now it's {table_name}_id_seq instead of using the {table_name}_seq convention

**Comment by AnatolyUss** [comment]
Hi Alejandro,
The convention for sequence names from what I read is <code>`${ tableName }_${ columnName }_seq`</code>.
That is why this convention was adopted in Nmig.
Furthermore, when you create a new table with <code>SERIAL</code> column using PgAdmin, the sequence name will have a form of <code>`${ tableName }_${ columnName }_seq`</code>.
Could you elaborate why this feature is necessary?

**Comment by amatosg** [comment]
you are correct, I totally misread a post in SO. I'm sorry :speak_no_evil:

**Comment by AnatolyUss** [comment]
Never mind ;-)
