### ISSUE TITLE
--[populateTableWorker] error: insert or update on table "abc" violates foreign key constraint

### ISSUE THREAD

**Issue by amatosg** [AnatolyUss/nmig#67]
hi!

As this is a migration, it is save to say that the data is consistent, so it would be a good idea to disable triggers on each table before inserting the data, once all data has been migrated, enable all triggers as suggested here: https://stackoverflow.com/a/38113838/1917300

Maybe I'm missing something?

**Comment by AnatolyUss** [comment]
Hi Alejandro,
Thanks for posting the issue.
The data transfer happens before enabling of keys, unless you're migrating the data into a preset schema.
Could you send me your configuration (connection details can be excluded)?

**Comment by amatosg** [comment]
I'm using a preset schema. I'll send the config when I get home. thanks!

**Comment by AnatolyUss** [comment]
Ok, understood. Definitely, it is "triggers" issue.
I'll fix it asap.

**Comment by AnatolyUss** [comment]
Hi,
The issue seems to be fixed.
Please, use the latest release (v4.0.2).
