### ISSUE TITLE
Use of COPY only works when PostgreSQL is on the same host as MySQL

### ISSUE THREAD

**Issue by ocharles** [AnatolyUss/nmig#7]
The way COPY is being used is not entirely optimal:

1. It requires that the PostgreSQL connection user has access to the CSV file
2. It assumes that the CSV file is on the same host as the PostgreSQL server.

I think it would be better to use the STDIN variation of `COPY`, which doesn't have these limitations.

**Comment by AnatolyUss** [comment]
Hi Oliver,
I must to note, that your statement in the title is wrong! 
MySQL DOES NOT have to be installed on the same machine as PostgreSQL.
Regarding flow optimization - I agree, that usually there is a "better way" to accomplish a task...
I'm not sure I'll have enough spare time this/next month to rewrite things. 
If you have enough spare time and would like to help - consider to fork the project, make changes, test them and share (make P.R.) - the "open source community" (including myself) will appreciate your efforts!
Thanks a lot for your remarks!

**Comment by ocharles** [comment]
Ok, you're right that it doesn't have to be on the same machine as MySQL - but you have to run nmig on same machine as PostgreSQL in order to benefit from COPY, that was more my point.

I'm not sure I'll be able to get a PR in as I'm not proficient in JavaScript and don't have the time to get up to scratch. I'll consider it.
