### ISSUE TITLE
Feature Request: What about Stored Procedures?

### ISSUE THREAD

**Issue by Tzahile** [AnatolyUss/nmig#70]
First of all, awesome tool!
Thanks for sharing this important ability of migrating from mySQL to postgreSQL.

I noticed non of my `stored procedures` has passed to the new db in postgreSQL.
I wonder - do you have plans on adding this feature?
Stored Procedures are important for all of the data management...
Thanks! 😃

**Comment by AnatolyUss** [comment]
Hey Tzahi,
Indeed, stored procedures are important, but Nmig does not migrate them.
Currently, I don't have plans to add this feature due to its complication
(SQL dialect conversion from MySQL to PostgreSQL).
Thanks for you feedback!
