### ISSUE TITLE
error: access method "fulltext" does not exist

### ISSUE THREAD

**Issue by alexthamm** [AnatolyUss/nmig#76]
Hi, I keep getting this error when trying to migrate my MySql DB to PostgreSQL:

```
--[IndexAndKeyProcessor::default] error: access method "fulltext" does not exist
                                                                                 
SQL: CREATE INDEX "public_pg_table_pg_varchar_field1_idx" 
          ON "public"."pg_table"  
           USING FULLTEXT ("pg_varchar_field");
```
nmig 5.4.0 (commit c8cec719b5fa9d0967b8e86ad907b889c8d385dd )
PostgreSQL 12.3
MySql 5.7.31

From DBeaver:

MySql field:
* Column Name: pg_varchar_field
* Data type: varchar(100)
* Key: MUL
* Charset: latin1
* Collation: latin1_swedish_ci

Generated PostgreSQL field:
* Column Name: pg_varchar_field
* Data type: varchar
* Length: 100
* Precision: 100
* Default: NULL::character varying
* Collation: default

I changed the table and field names for this ticket as I'm not sure if I'm allowed to use the original names.

Please let me know if you need anything else.

**Comment by AnatolyUss** [comment]
Hi Alexander,
My apologies for the late response.
PostgreSQL's full-text search doesn't work the same way MySQL's does.
PostgreSQL doesn't have the <code>FULLTEXT</code> index.

Probably the closest match to <code>FULLTEXT</code> is the <code>GIN</code> index.
Notice, the column must be of type <code>TSVECTOR</code> to use <code>GIN</code> index.

Regarding this specific error, you can safely ignore it.
I guess it didn't crash the entire migration process ))

After migration completion, consider to:
1. Change a type of <code>"pg_varchar_field"</code> from <code>VARCHAR</code> to <code>TSVECTOR</code>. 
2. Create a <code>GIN</code> index on the <code>"pg_varchar_field"</code> column.
