### ISSUE TITLE
Read RPC timeout

### ISSUE THREAD

**Issue by danports** [AnatolyUss/nmig#77]
After converting a bunch of tables, nmig is crashing in the middle of a run with the following output:
```
        --[TableProcessor::createTable] error: Timed out: Read RPC (request call id 80) to 127.0.0.1:7100 timed out after 60.000s

        SQL: CREATE TABLE IF NOT EXISTS "public"."alerts"("Id" int, ... [rest of table definition] ... );

npm ERR! code 1
npm ERR! path /nmig/nmig
npm ERR! command failed
```

The referenced log file doesn't contain any additional information.

Any suggestions?

**Comment by AnatolyUss** [comment]
Hi Dan,
Which PostgreSQL version are you using?
Could you try to restart Nmig?
<code>$ npm start</code> or <code>$ npm start -- --conf-dir='/path/to/nmig_config' --logs-dir='/path/to/nmig_logs'</code>
