### ISSUE TITLE
Triggers from mysql 5.5

### ISSUE THREAD

**Issue by woutervantoledo** [AnatolyUss/nmig#80]
Hi! We're trying to convert several databases from mysql 5.5 (yeah, it's ooold) to postgresql 13 with nmig 5.5.0
We've done several testmigrations, but for some reason the triggers are not migrated. 
We cannot find anything in nmig on if this is expected or not.
How can we also migrate the triggers?

**Comment by AnatolyUss** [comment]
Hello,
For now, triggers migration is not implemented.

I would suggest to, kind of, "copy and adjust" triggers manually, right
after nmig's migration completion.

**Comment by woutervantoledo** [comment]
Clear. Thanks for the reply.
We will do an export from MySQL adjust and create in postgresql.
