### ISSUE TITLE
OOM errors on very large table

### ISSUE THREAD

**Issue by mylapstemp** [AnatolyUss/nmig#82]
Hi! Wonderful tool, but I have one problem: on migrating a 52GB table I get:

        --[loadData] Loading the data into "public"."event_upload_binary" table...

<--- Last few GCs --->

[7064:0x5560f92e45f0]    20237 ms: Mark-sweep 1321.3 (1454.8) -> 1321.3 (1438.8) MB, 24.3 / 0.0 ms  (average mu = 0.455, current mu = 0.001) last resort GC in old space requested
[7064:0x5560f92e45f0]    20263 ms: Mark-sweep 1321.3 (1438.8) -> 1321.3 (1438.8) MB, 25.7 / 0.0 ms  (average mu = 0.289, current mu = 0.001) last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2f449b4e6f41]
Security context: 0x2f3069ee3a69 <JSObject>
    1: stringSlice(aka stringSlice) [0x1ae152c134b9] [buffer.js:~589] [pc=0x2f449b4e71ab](this=0x038fb39026f1 <undefined>,buf=0x3b4448c7e8e9 <Uint8Array map = 0x26809f9d0071>,encoding=0x2f3069eeca99 <String[5]: utf-8>,start=11,end=1314259)
    2: _typeCast(aka typeCast) [0x1034bf702d69] [/etc/nmig/nmig/node_modules/mysql/lib/protocol/packets/RowDataPacket.js...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x5560f61d5e74 node::Abort() [/usr/bin/node]
 2: 0x5560f61d5ec2  [/usr/bin/node]
 3: 0x5560f63cdaaa v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0x5560f63cdd25 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0x5560f677f0a6  [/usr/bin/node]
 6: 0x5560f67948a8 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/bin/node]
 7: 0x5560f6760dcd v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map*, v8::internal::AllocationAlignment) [/usr/bin/node]
 8: 0x5560f6768148 v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/bin/node]
 9: 0x5560f6768412 v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const>, v8::internal::PretenureFlag) [/usr/bin/node]
10: 0x5560f67687a2 v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/usr/bin/node]
11: 0x5560f63daaab v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [/usr/bin/node]
12: 0x5560f62a5069 node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding, v8::Local<v8::Value>*) [/usr/bin/node]
13: 0x5560f61f3488  [/usr/bin/node]
14: 0x2f449b4e6f41

Any way to increase the memory available to the tool?

**Comment by AnatolyUss** [comment]
Hello,
Yes.
Please, have a look at <code>/nmig/config/config.json</code>, the <code>loader_max_old_space_size</code> parameter.
It allows you to adjust V8 memory limit of each data loader process.
Possible values are:
1. Any positive integer, representing V8 memory limit (in MB).
2. <code>DEFAULT</code>, representing V8 default memory limit for your current hardware.
