### ISSUE TITLE
Tables names convert to lowercase

### ISSUE THREAD

**Issue by joelpj** [AnatolyUss/nmig#83]
It's possible when migrating MySQL database to PostgreSQL change all objects names to lowercase to match Postgres naming conventions?

**Comment by AnatolyUss** [comment]
Hello Joel,
Technically, of course, it is possible.
Yet, for now, it isn't a part of the roadmap.

**Comment by Luca8991** [comment]
I'd also be interested in this to make sure the migrated db follows PostgreSQL conventions

**Comment by Luca8991** [comment]
@AnatolyUss do you have some hints on how to achieve it? I need my MySQL db to be migrated to PostgreSQL using [snake_case naming convention](https://stackoverflow.com/a/2878408/5094892)

**Comment by AnatolyFromPerion** [comment]
@Luca8991 @joelpj 
You can achieve it by renaming.

Have a look at <code>/nmig/config/extra_config.json</code>
Follow instructions under <code>README_RENAMING</code> and <code>README_FKs</code> sections.
Once done with the extra-config, go to <code>/nmig/config/config.json) and set <code>"enable_extra_config": true</code>

Of course, if you have a large schema where every table and every column is camel-cased, it may take you some time to fill up this config.
