### ISSUE TITLE
Allow for conversion using IDENTITY instead of SEQUENCE or SERIAL

### ISSUE THREAD

**Issue by chamby** [AnatolyUss/nmig#87]
The modern PostgreSQL approach to primary auto-incrementing indexes seems to be `IDENTITY` rather than `SERIAL` or the even more verbose `SEQUENCE`.

https://www.2ndquadrant.com/en/blog/postgresql-10-identity-columns/

**Comment by chamby** [comment]
@AnatolyFromPerion `IDENTITY` does implicitly use sequences, but I thought the [linked article](https://www.2ndquadrant.com/en/blog/postgresql-10-identity-columns/) did a good job explaining some benefits. It seems the focus is on the benefits of `IDENTITY` over `SERIAL`, so that does not apply to nmig. Other than being the recommended approach the main benefit seems to be easier and more concise `ALTER` commands when dealing with `IDENTITY`. Adding, modifying, and dropping `IDENTITY` columns is an improvement IMO over working with sequences.

As far as version support that is up to you. `10.x` has been available for 4 years and `9.x` is [no longer officially supported](https://www.postgresql.org/support/versioning/). If a goal of nmig is broad version support then I understand your desire to keep using `SEQUENCE`.

**Comment by AnatolyFromPerion** [comment]
@chamby 
Sorry, I missed that <code>PG 9.x</code> is no longer supported.
Thanks!

Just posted a comment to your p.r.

**Comment by AnatolyUss** [comment]
@chamby 
Just merged your p.r.
Thanks for the contribution!
