### ISSUE TITLE
Multiple COPY errors

### ISSUE THREAD

**Issue by gjuchault** [AnatolyUss/nmig#9]
Hi,

While migrating a database (on windows), some table outputs errors :
`--[populateTableWorker] error: could not open file "path\to\csvfile.csv" for reading: Permission denied
`

**Comment by fjfalcon** [comment]
Well, i am not developer of nmig, but you better check that user, from witch you run nmig have write access to directory  "path\to".

**Comment by AnatolyUss** [comment]
Hi,
In addition to previous comment, make sure that PostgreSQL user, that you've mentioned in "target"->"user" have privileges of superuser.

**Comment by gjuchault** [comment]
I was using a super user with an admin command prompt in a user directory.
What is strange is that multiple files are written, but not some, and the error is Permission denied and not file not found (I could'nt see the file myself)

**Comment by fjfalcon** [comment]
well, for example you can make chmod 777 "/path/to" to test all works fine.
But aftet that you should remove dir, cause it's really totally not secure.

**Comment by fjfalcon** [comment]
Also, maybe your tables name length more then 255 chars? Cause linux filesystem don't allow filename longer than 255 chars.

**Comment by gjuchault** [comment]
> well, for example you can make chmod 777 "/path/to" to test all works fine.
> But aftet that you should remove dir, cause it's really totally not secure.

> Also, maybe your tables name length more then 255 chars? Cause linux filesystem don't allow filename longer than 255 chars.

Actually I'm on Windows. So I had every right to create/read files from the directory. I'd think that was coming from a file written then unlinked and nmig tried to read after sending unlink; I don't really know so I made migration by hand

**Comment by AnatolyUss** [comment]
Could you send me the "errors-only.log" file?

**Comment by gjuchault** [comment]
Sorry I just did the migration days ago and didn't keep any of the errors files.. But there was no more of what I pasted on the first message (I took that from the log).

**Comment by AnatolyUss** [comment]
No problem, thanks for the feedback!
BTW, did you accomplish the migration using nmig, or some other app?
If you've used nmig, then how much time did it take and what was the size of your database?

**Comment by gjuchault** [comment]
The database was 23 Go. I think that may have caused some trouble to node (taking all my RAM). So I did all by myself. nmig created the database structure; then I dumped all the data to CSV file, and I used COPY to import all of theses. It took like 2 days to migrate everything (this is still a good number; when on the postgres it's written that you need 6 months)
