### ISSUE TITLE
current_timestamp() not working as default value of field in Postgresql

### ISSUE THREAD

**Issue by proset-dev-central** [AnatolyUss/nmig#95]
In a migration from mysql to postgres when a column in mysql has default of current_timstamp() an error is produced due to the fact that in postgres the syntax is current_timestamp without parenthesis. Or the equivalent is now()   with parenthesis

**Comment by AnatolyUss** [comment]
Thanks for pointing that out!
I'll fix it asap.

**Comment by AnatolyFromPerion** [comment]
Finally fixed!

**Comment by proset-dev-central** [comment]
Thanks!

 

 

Proset
